# 01 - Limpieza de los datos

Aqui dejamos la tabla lista para analizar. Si cambian el dataset, solo cambian la ruta del archivo.

In [146]:
import sys
sys.path.append('../src')
from limpieza import cargar_datos, quitar_nulos, quitar_duplicados, resumen

In [147]:
tabla = cargar_datos('../data/datos_reales.csv')

Filas: 3000
Columnas: ['genero', 'zona', 'depto', 'municipio', 'estrato', 'educacion_madre', 'educacion_padre', 'internet', 'matematicas', 'lectura', 'global', 'periodo']

In [148]:
tabla.head()

,genero,zona,depto,municipio,estrato,educacion_madre,educacion_padre,internet,matematicas,lectura,global,periodo
0,F,URBANO,CAQUETA,EL DONCELLO,Estrato 2,Primaria incompleta,Primaria incompleta,No,44,50,237,20224
1,F,URBANO,QUINDIO,ARMENIA,Estrato 2,Educación profesional completa,No Aplica,Si,42,40,214,20224
2,M,RURAL,ANTIOQUIA,ANDES,Estrato 2,Primaria incompleta,Primaria incompleta,No,58,59,278,20224
3,F,URBANO,ANTIOQUIA,BELLO,Estrato 3,Educación profesional completa,No sabe,Si,53,47,254,20224
4,M,URBANO,VALLE,PALMIRA,Estrato 2,Técnica o tecnológica completa,No sabe,Si,71,69,341,20224

In [149]:
print(nulos_por_campo / len(tabla) * 100)

genero             0.0
zona               0.0
depto              0.0
municipio          0.0
estrato            0.0
educacion_madre    0.0
educacion_padre    0.0
internet           0.0
matematicas        0.0
lectura            0.0
global             0.0
periodo            0.0
dtype: float64

In [150]:
tabla = quitar_nulos(tabla)

Se quitaron 499 filas con vacios

In [151]:
resumen(tabla)

<class 'pandas.DataFrame'>
Index: 2501 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   genero           2501 non-null   str
 1   zona             2501 non-null   str
 2   depto            2501 non-null   str
 3   municipio        2501 non-null   str
 4   estrato          2501 non-null   str
 5   educacion_madre  2501 non-null   str
 6   educacion_padre  2501 non-null   str
 7   internet         2501 non-null   str
 8   matematicas      2501 non-null   int64
 9   lectura          2501 non-null   int64
 10  global           2501 non-null   int64
 11  periodo          2501 non-null   int64
dtypes: int64(4), str(8)
memory usage: 254.0 KB
None
       matematicas      lectura       global  periodo
count  2501.000000  2501.000000  2501.000000   2501.0
mean     50.428629    52.728109   250.261495  20224.0
std      12.724944    11.170553    54.011306      0.0
min      18.000000    25.000000   137.000000  20224.0
25%      41.000000    45.000000   208.000000  20224.0
50%      51.000000    53.000000   246.000000  20224.0
75%      59.000000    61.000000   288.000000  20224.0
max     100.000000   100.000000   448.000000  20224.0

       matematicas      lectura       global  periodo
count  2501.000000  2501.000000  2501.000000   2501.0
mean     50.428629    52.728109   250.261495  20224.0
std      12.724944    11.170553    54.011306      0.0
min      18.000000    25.000000   137.000000  20224.0
25%      41.000000    45.000000   208.000000  20224.0
50%      51.000000    53.000000   246.000000  20224.0
75%      59.000000    61.000000   288.000000  20224.0
max     100.000000   100.000000   448.000000  20224.0

In [152]:
tabla.to_csv('../data/datos_limpios.csv', index=False)
print('Guardado en datos_limpios.csv')

Guardado en datos_limpios.csv