# 01 - Limpieza de los datos

Aqui dejamos la tabla lista para analizar. Los vacios no se borran, se tratan
con la categoria "No informado" para no perder registros. Si cambian el
dataset, solo cambian la ruta del archivo.

In [1]:
import sys
sys.path.append('../src')
from limpieza import cargar_datos, tratar_nulos, quitar_duplicados, resumen

In [2]:
tabla = cargar_datos('../data/datos_reales.csv')

Filas: 3000
Columnas: ['genero', 'zona', 'depto', 'municipio', 'estrato', 'educacion_madre', 'educacion_padre', 'internet', 'matematicas', 'lectura', 'global', 'periodo']

In [3]:
tabla.head()

,genero,zona,depto,municipio,estrato,educacion_madre,educacion_padre,internet,matematicas,lectura,global,periodo
0,F,URBANO,CAQUETA,EL DONCELLO,Estrato 2,Primaria incompleta,Primaria incompleta,No,44,50,237,20224
1,F,URBANO,QUINDIO,ARMENIA,Estrato 2,Educación profesional completa,No Aplica,Si,42,40,214,20224
2,M,RURAL,ANTIOQUIA,ANDES,Estrato 2,Primaria incompleta,Primaria incompleta,No,58,59,278,20224
3,F,URBANO,ANTIOQUIA,BELLO,Estrato 3,Educación profesional completa,No sabe,Si,53,47,254,20224
4,M,URBANO,VALLE,PALMIRA,Estrato 2,Técnica o tecnológica completa,No sabe,Si,71,69,341,20224

In [4]:
nulos_por_campo = tabla.isna().sum()
print(nulos_por_campo)
print()
print('Filas con al menos un vacio:', int(tabla.isna().any(axis=1).sum()))

genero               0
zona                 0
depto                0
municipio            0
estrato            466
educacion_madre    443
educacion_padre    434
internet           442
matematicas          0
lectura              0
global               0
periodo              0
dtype: int64

Filas con al menos un vacio: 499

In [5]:
tabla = tratar_nulos(tabla)

Filas con al menos un vacio: 499
Nulos por columna antes del tratamiento:
estrato            466
educacion_madre    443
educacion_padre    434
internet           442
dtype: int64

Nulos despues del tratamiento:
genero             0
zona               0
depto              0
municipio          0
estrato            0
educacion_madre    0
educacion_padre    0
internet           0
matematicas        0
lectura            0
global             0
periodo            0
dtype: int64

In [6]:
tabla = quitar_duplicados(tabla)

Se quitaron 0 filas repetidas

In [7]:
resumen(tabla)

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   genero           3000 non-null   str
 1   zona             3000 non-null   str
 2   depto            3000 non-null   str
 3   municipio        3000 non-null   str
 4   estrato          3000 non-null   str
 5   educacion_madre  3000 non-null   str
 6   educacion_padre  3000 non-null   str
 7   internet         3000 non-null   str
 8   matematicas      3000 non-null   int64
 9   lectura          3000 non-null   int64
 10  global           3000 non-null   int64
 11  periodo          3000 non-null   int64
dtypes: int64(4), str(8)
memory usage: 281.4 KB

None

       matematicas      lectura       global  periodo
count  3000.000000  3000.000000  3000.000000   3000.0
mean     49.689667    52.193667   246.853667  20224.0
std      12.710752    11.147956    53.725013      0.0
min      17.000000    24.000000   123.000000  20224.0
25%      40.000000    44.000000   205.000000  20224.0
50%      50.000000    52.000000   241.000000  20224.0
75%      58.000000    60.000000   285.000000  20224.0
max     100.000000   100.000000   448.000000  20224.0

       matematicas      lectura       global  periodo
count  3000.000000  3000.000000  3000.000000   3000.0
mean     49.689667    52.193667   246.853667  20224.0
std      12.710752    11.147956    53.725013      0.0
min      17.000000    24.000000   123.000000  20224.0
25%      40.000000    44.000000   205.000000  20224.0
50%      50.000000    52.000000   241.000000  20224.0
75%      58.000000    60.000000   285.000000  20224.0
max     100.000000   100.000000   448.000000  20224.0

In [8]:
tabla.to_csv('../data/datos_limpios.csv', index=False)
print('Guardado en datos_limpios.csv')

Guardado en datos_limpios.csv